"""
auth.py
-------
Replaces streamlit-authenticator. Same idea, different mechanism:

- Your username/password (hashed) live in environment variables, not a file,
  since this now needs to work the same locally and on Render.
- On login, we don't "remember" the user with a cookie like Streamlit did --
  instead we hand back a signed token (JWT). The frontend stores that token
  and sends it with every future request in a header. The server checks the
  token's signature on each request to confirm "yes, this is really a
  logged-in user" -- this is what answers your security question: a token
  can't be guessed or forged without the secret key, which only the server
  has. There's no URL-based session to hijack because there IS no session
  state tied to a URL.
"""

import os
from datetime import datetime, timedelta, timezone

from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from jose import jwt, JWTError
from passlib.context import CryptContext

SECRET_KEY = os.environ.get("JWT_SECRET", "dev-only-secret-change-this")
ALGORITHM = "HS256"
TOKEN_EXPIRE_HOURS = 12

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
bearer_scheme = HTTPBearer()

# Single demo user, defined via environment variables (set these on Render
# as Secrets, and locally in a .env file). No database needed for one user.
APP_USERNAME = os.environ.get("APP_USERNAME", "admin")
APP_PASSWORD_HASH = os.environ.get("APP_PASSWORD_HASH")  # generated by generate_password_hash.py


def verify_credentials(username: str, password: str) -> bool:
    if username != APP_USERNAME or not APP_PASSWORD_HASH:
        return False
    return pwd_context.verify(password, APP_PASSWORD_HASH)


def create_access_token(username: str) -> str:
    expire = datetime.now(timezone.utc) + timedelta(hours=TOKEN_EXPIRE_HOURS)
    payload = {"sub": username, "exp": expire}
    return jwt.encode(payload, SECRET_KEY, algorithm=ALGORITHM)


def get_current_user(credentials: HTTPAuthorizationCredentials = Depends(bearer_scheme)) -> str:
    """
    FastAPI dependency. Add `user: str = Depends(get_current_user)` to any
    endpoint to require a valid token -- FastAPI calls this automatically
    before running the endpoint, and rejects the request with 401 if the
    token is missing, expired, or tampered with.
    """
    token = credentials.credentials
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        username = payload.get("sub")
        if username is None:
            raise HTTPException(status_code=401, detail="Invalid token")
        return username
    except JWTError:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid or expired token")
