"""
quiz_engine.py
--------------
Handles the two LLM jobs Quiz Mode needs:
  1. Generate N questions spread across the uploaded PDF(s)
  2. Grade a user's answer against the actual source chunk it came from

Why we tie each question to one specific chunk:
Grading "from the PDF itself" only works if we know exactly which part of
the PDF the question is about. So every generated question carries its
source chunk along with it -- that's what gets sent back to the LLM at
grading time, instead of re-searching the vector store.
"""

import json
import random


def _pick_spread_chunks(chunks, n):
    """
    Pick n chunks spread evenly across the document instead of n random ones.
    This avoids the quiz being 5 questions all from the first page just
    because that's where random.sample happened to land.
    """
    if len(chunks) <= n:
        return list(chunks)
    step = len(chunks) / n
    indices = [int(i * step) for i in range(n)]
    return [chunks[i] for i in indices]


def generate_questions(client, model, chunks, n):
    """
    Returns a list of dicts: {question, source_text, source, page}
    One question per selected chunk, generated by the LLM.
    """
    selected = _pick_spread_chunks(chunks, n)
    questions = []

    for chunk in selected:
        prompt = (
            "Based ONLY on the following text, write ONE clear study question "
            "that tests understanding of its key concept. Do not include the answer. "
            "Return ONLY the question text, nothing else.\n\n"
            f"Text:\n{chunk.text}"
        )
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.4,
        )
        question_text = response.choices[0].message.content.strip()
        questions.append({
            "question": question_text,
            "source_text": chunk.text,
            "source": chunk.source,
            "page": chunk.page,
        })

    random.shuffle(questions)
    return questions


def generate_mcq_questions(client, model, chunks, n):
    """
    Same idea as generate_questions, but asks for 4 options + the correct
    one. Returned as structured JSON so the frontend can render clickable
    options without any text parsing.
    """
    selected = _pick_spread_chunks(chunks, n)
    questions = []

    for chunk in selected:
        prompt = (
            "Based ONLY on the following text, write ONE multiple-choice question "
            "testing its key concept. Provide exactly 4 options where only one is correct. "
            "Respond with ONLY valid JSON, no markdown, in this exact shape:\n"
            '{"question": "...", "options": ["...", "...", "...", "..."], "correct_index": <0-3>}\n\n'
            f"Text:\n{chunk.text}"
        )
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.4,
        )
        raw = response.choices[0].message.content.strip()
        raw = _strip_json_fences(raw)
        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError:
            continue  # skip a malformed question rather than crash the whole quiz

        questions.append({
            "question": parsed["question"],
            "options": parsed["options"],
            "correct_index": int(parsed["correct_index"]),
            "source": chunk.source,
            "page": chunk.page,
        })

    random.shuffle(questions)
    return questions


def grade_mcq_answer(question, selected_index):
    """No LLM call needed -- MCQ grading is a simple equality check."""
    correct = selected_index == question["correct_index"]
    return {
        "score": 10 if correct else 0,
        "verdict": "correct" if correct else "incorrect",
        "missing_points": [],
        "feedback": "Correct." if correct else f"The correct answer was: {question['options'][question['correct_index']]}",
    }


def _strip_json_fences(raw):
    if raw.startswith("```"):
        raw = raw.strip("`")
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.strip()
    return raw

def grade_answer(client, model, question, source_text, user_answer):
    """
    Grades the user's answer using ONLY the source chunk as ground truth.
    Returns a dict: {score (0-10), verdict, missing_points (list), feedback}
    We ask the LLM to return strict JSON so the UI can render structured
    feedback instead of parsing free-form prose.
    """
    prompt = f"""You are grading a student's answer using ONLY the source text below as the ground truth. Do not use outside knowledge.

Source text:
{source_text}

Question: {question}

Student's answer: {user_answer}

Grade the answer and respond with ONLY valid JSON in this exact shape, no markdown, no preamble:
{{
  "score": <integer 0-10>,
  "verdict": "<one of: correct, partially correct, incorrect>",
  "missing_points": [<short list of key points the answer missed, empty list if none>],
  "feedback": "<one short sentence of feedback>"
}}"""

    response = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
    )
    raw = response.choices[0].message.content.strip()
    raw = _strip_json_fences(raw)

    try:
        result = json.loads(raw)
    except json.JSONDecodeError:
        # Fallback so a single bad LLM response doesn't crash the quiz
        result = {
            "score": 0,
            "verdict": "incorrect",
            "missing_points": [],
            "feedback": "Could not grade this answer automatically -- try rephrasing it.",
        }

    result["score"] = max(0, min(10, int(result.get("score", 0))))
    return result
